CREATE TABLE tb_gasto (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(100),
    valor NUMBER(10,2),
    categoria VARCHAR2(50),
    moeda VARCHAR2(10),
    valor_convertido NUMBER(10,2),
    data DATE,
    usuario_id NUMBER,
    CONSTRAINT fk_usuario FOREIGN KEY (usuario_id)
        REFERENCES tb_usuario_financas(id)
);